config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'site#homepage'
  resources :events do
    get 'reparse_park_data', on: :collection
    post 'search_events'
  end
  patch 'join' => 'events#join', as: 'join_event'
  patch 'unjoin' => 'events#unjoin', as: 'unjoin_event'
  get 'my_joined_events' => 'events#my_joined_events', as: 'my_joined_events'
  get 'my_created_events' => 'events#my_created_events', as: 'my_created_events'
  get 'this_park_events' => 'events#this_park_events', as: 'this_park_events'
  post '/events/search' => 'events#search', :as => 'search'

  resources :parks do
    get 'reparse_park_data', on: :collection
  end

end

app/models/park.rb
class Park < ActiveRecord::Base

  require 'nokogiri'
  require 'open-uri'
  has_many :events

  @@numParks = 250

  def self.validator(doc)
    status = true
    if doc.at('COVParksFacilities') != nil
      docParksFacilities = doc.xpath('COVParksFacilities')
      parks = doc.xpath("//*[@ID]")
      if parks.size > 0 && parks.size < @@numParks
        for i in 0..parks.size-1
          park = parks[i].xpath('Name')
          if park == nil
            status = false
          end
        end
      else 
        status = false
      end
    else
      status = false
    end
    return status
  end

  def self.XMLparser
    Park.destroy_all
    suckr = ImageSuckr::GoogleSuckr.new
    doc = Nokogiri::XML(open('ftp://webftp.vancouver.ca/opendata/xml/parks_facilities.xml'))
    if validator(doc)
      doc.xpath("//Park").each do |node|
        puts "Park ID = " + node.attr("ID")
        parkname = node.at("Name").text
        image_url = suckr.get_image_url({"q" => "#{parkname} Vancouver"})
        Park.create!(
          id: (node.attr("ID")).to_i,
          name: node.at("Name").text,
          streetNumber: node.at("StreetNumber").text.to_i,
          streetName: node.at("StreetName").text,
          ewStreet:node.at("EWStreet").text,
          washroom:node.at("Washroom").text,
          nsstreet:node.at("NSStreet").text,
          googleMapDest:node.at("GoogleMapDest").text,
          hectare:node.at("Hectare").text
          )
      end
    else
      Rails.logger.info(">>>>>>>>>>>>>>> ERROR: INVALID XML RECEIVED <<<<<<<<<<<<<<<")
    end
  end

  def self.XMLparseralternate
    Park.destroy_all
    suckr = ImageSuckr::GoogleSuckr.new
    doc = Nokogiri::XML(open('ftp://webftp.vancouver.ca/opendata/xml/parks_facilities.xml'))
    if validator(doc)
      doc.xpath("//Park").each do |node|
        puts "Park ID = " + node.attr("ID")
        parkname = node.at("Name").text
        image_url = suckr.get_image_url({"q" => "#{parkname} Vancouver"})
        Park.create!(
          id: (node.attr("ID")).to_i,
          name: node.at("Name").text,
          streetNumber: node.at("StreetNumber").text.to_i,
          streetName: node.at("StreetName").text,
          ewStreet:node.at("EWStreet").text,
          washroom:node.at("Washroom").text,
          nsstreet:node.at("NSStreet").text,
          googleMapDest:node.at("GoogleMapDest").text,
          hectare:node.at("Hectare").text,
          image_url: image_url
          )
      end
    else
      Rails.logger.info(">>>>>>>>>>>>>>> ERROR: INVALID XML RECEIVED <<<<<<<<<<<<<<<")
    end
  end
  
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
	layout 'event_park_layout'
		before_action :build_park_array, only: [:index]
		before_action :authenticate_user!, only: [:show, :index]

	def index
		@type = "index"
		@park_list = Park.all.order(name: :asc)
		@parks = @park_list.map{|x| [x.googleMapDest.split(',').first.to_f, x.googleMapDest.split(',').second.to_f, x.name, x.streetNumber, x.streetName, ["Playgrounds"], x.id]}
		@title = "Parks"
	end

	def reparse_park_data
		@helper = Park.XMLparser
		redirect_to events_path
	end

	private 

	def build_park_array
			@parks = Park.all
			@parksmap = @parks.map{|x| [x.googleMapDest.split(',').first.to_f, x.googleMapDest.split(',').second.to_f, x.name, x.streetNumber, x.streetName, ["Playgrounds"], x.id]}
			@parksmap2 = @parks.map{|x| [x.googleMapDest.split(',').first.to_f, x.googleMapDest.split(',').second.to_f, x.id]}
	end

end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/parks/index.html.erb
<div class="col-md-8 map-container" style="padding-left: 0px;padding-right: 0px; height: 100%">
  <div id="mapnew" style='width: 100%; height: 800px;'></div>
</div>
<div class="col-md-4 whitefullheight">

  <%= render 'sub_navbar' %>

  <h2 style="font-weight: bold"><%= @title %></h2>
  <div class="container-fluid nopad" id="parkscontainer" style="height: 500px; overflow-y: scroll;overflow-x: hidden;">

    <% @park_list.each do |park| %>
    
    <div class="panel panel-default" id="<%= park.id %>">
      <div class="panel-heading"><%= park.name %></div>
      <div class="panel-body" style="width:100%">
        <%= image_tag(park.image_url, width: '100%') %>
      </div>
      <div class="panel-body">
        <%= park.streetNumber %> <%= park.streetName %>
      </div>
      <div class="panel-footer"><%= link_to "View Events", this_park_events_path(:park_param => park.id), class: "btn btn-primary btn-xs" %><%= link_to "Create Event", new_event_path(:park_param => park.id), class: "btn btn-primary btn-xs" %></div>
    </div>

    <% end %>

  </div>
</div>

<%= render 'map_script' %>