config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'site#homepage'
  resources :events do
    get 'reparse_park_data', on: :collection
    post 'search_events'
  end
  patch 'join' => 'events#join', as: 'join_event'
  patch 'unjoin' => 'events#unjoin', as: 'unjoin_event'
  get 'my_joined_events' => 'events#my_joined_events', as: 'my_joined_events'
  get 'my_created_events' => 'events#my_created_events', as: 'my_created_events'
  get 'this_park_events' => 'events#this_park_events', as: 'this_park_events'
  post '/events/search' => 'events#search', :as => 'search'

  resources :parks do
    get 'reparse_park_data', on: :collection
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :title, :presence => true
	validates :date, :presence => true
	validates :time, :presence => true
	validates_date :date, :on_or_after => Date.today

	belongs_to :park
	has_and_belongs_to_many :users
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	layout 'event_park_layout'

	before_action :find_event, only: [:show, :edit, :update, :destroy, :join, :unjoin]
	before_action :build_park_array, only: [:index, :new, :show, :edit, :my_joined_events, :my_created_events, :this_park_events, :search]
	before_action :authenticate_user!, only: [:new, :show, :edit, :update, :destroy, :my_joined_events, :my_created_events, :this_park_events, :search]
	skip_before_filter :verify_authenticity_token, :only => [:search]

	def index
		@events = Event.all.where("date >= current_date").order(date: :asc)
		build_park_array
		@type = "index"
		@title = "All Events"
	end

	def reparse_park_data
		@helper = Park.XMLparser
		redirect_to events_path
	end

	def new
		@type = "new"
		@park_id = params[:park_param]
		@event = current_user.events.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			current_user.events << @event
			@event.update(:creator_id => current_user.id)
			redirect_to events_url, :flash => { :notice => "#{@event.title} has been successfully created" }
		else
			@parks = Park.all
			
			render :new
		end
	end

	def show
	end

	def edit
		@park_id = params[:park_param]
	end

	def update
		if @event.update(event_params)
			redirect_to @event
		else
			@parks = Park.all
			render "edit"
		end    
	end

  # DELETE /events/1
  def destroy
  	@event.destroy
  	redirect_to events_url
  end

  def join
  	if !@event.users.exists?(current_user.id)
  		current_user.events << @event
  		redirect_to @event, :flash => { :notice => "You have successfully joined #{@event.title}" }
  	else
  		redirect_to @event, :flash => { :alert => "You are already on the list for #{@event.title}" }
  	end
  end

  def unjoin
  	if  @event.users.exists?(current_user.id)
  		current_user.events.delete(@event)
  		redirect_to @event, :flash => { :notice => "You have successfully unjoined #{@event.title}" }
  	else
  		redirect_to @event, :flash => { :alert => "You had never joined #{@event.title}" }
  	end
  end

  def my_joined_events
  	@events = Event.all.where("creator_id = #{current_user.id}").where("date >= current_date").order(date: :asc)
  	@title = "My Joined Events"
  	render "index"
  end

  def my_created_events
  	@events = current_user.events.where("date >= current_date").order(date: :asc)
  	@title = "My Created Events"
  	render "index"
  end

  def this_park_events
  	this_park_id = params[:park_param]
  	@park = Park.find(this_park_id)
  	@events = Event.all.where("park_id = #{this_park_id}").where("date >= current_date")
  	@title = "Events at #{@park.name}"
  	render "index"
  end

  def search
  	query = params[:query]
  	@events = Event.all.where("title LIKE '%#{query}%'")
  	render "index"
  end

  private
  
  def event_params
  	params.require(:event).permit(:title, :date, :spots, :description, :park_id, :time, :query)
  end

  def find_event
  	@event = Event.find(params[:id])
  end

  def build_park_array
  	@parks = Park.all
  	@parksmap = @parks.map{|x| [x.googleMapDest.split(',').first.to_f, x.googleMapDest.split(',').second.to_f, x.name, x.streetNumber, x.streetName, ["Playgrounds"], x.id]}
  	@parksmap2 = @parks.map{|x| [x.googleMapDest.split(',').first.to_f, x.googleMapDest.split(',').second.to_f, x.id]}
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |form| %>

<% if @event.errors.any? %>
<div id="error_explanation">
	<ul>
		<% @event.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<table>
	<tr>
		<td><%= form.label :title, "Event Title:" %></td>
		<td><%= form.text_field :title %></td>
	</tr>

	<tr>
		<td><%= form.label :park_id, "Park:" %></td>
		<td><%= form.collection_select :park_id, @parks.order(:name), :id,:name, {:selected => @park_id }, include_blank: false %></td>
	</tr>
	<tr>
		<td><%= form.label :date, "Event Date:" %></td>
		<td>
			<%= form.date_field :date, min: Date.today %>
		</td>
	</tr>
	<tr>
		<td><%= form.label :time, "Event Time:" %></td>
		<td>
			<%= form.time_select :time, :default => @event.time, :ampm => true, :minute_step => 15 %>
		</td>
	</tr>
	<tr>
		<td><%= form.label :spots, "Number of Spots:" %></td>
		<td><%= form.number_field :spots, :value => 2, in: 2.0..100.0 %></td>
	</tr>
	<tr>
		<td><%= form.label :description, "Event Description:" %></td>
		<td><%= form.text_area :description %></td>
	</tr>	
</table>

<% if @event.errors[:event].any? %>
<p class='error messages'>
	The event <%= @event.errors[:event].to_sentence %>.
</p>
<% end %>

</br>
<%= link_to 'Events', events_path, class: "btn btn-default" %>
<%= form.submit :class => 'btn btn-success' %>
<% end %>

app/views/events/edit.html.erb
<div class="col-md-8 map-container" style="padding-left: 0px;padding-right: 0px; height: 100%">
	<div id="mapnew" style='width: 100%; height: 800px;'></div>
</div>
<div class="col-md-4 whitefullheight">

	<h2>Edit your Event</h2>

	<%= render 'form' %>

	<%= render 'map_script' %>

app/views/events/index.html.erb
<div class="col-md-8 map-container" style="padding-left: 0px;padding-right: 0px; height: 100%">
  <div id="mapnew" style='width: 100%; height: 800px;'></div>
</div>
<div class="col-md-4 whitefullheight">

  <%= render 'sub_navbar' %>

  <h2 class = "event-content"> <%= @title %></h2>
  <p> Tip: Use satellite view, then scroll in to get a bird's eye view of the parks</p>
  <div>
    <table class="table table-bordered table-hover event-content">
      <thead>
        <tr>
          <th class="table-header">Title</th>
          <th class="table-header" style="text-align:center">Park</th>
          <th class="table-header" style="text-align:center">Date</th>
          <th class="table-header" style="text-align:center">Time</th>
          <th class="table-header" style="text-align:center">Spots Available</th>
        </tr>
      </thead>

      <tbody class="table-body">
        <% @events.each do |event| %>
        <tr>
          <% if user_signed_in? %>
          <td class="table-body"><%= link_to event.title, event %></td>
          <% else %>
          <td ><%= event.title %></td>
          <% end %>
          <% if Park.find_by(id: event.park_id) == nil %>
          <td class="table-body" col align="center"> Data for park <%= event.park_id %> unavailable</td>
          <% else %>
          <td class="table-body" col align="center"><%= Park.find_by(id: event.park_id).name %></td>
          <% end %>
          <td class="table-body" col align="center"><%= event.date.to_formatted_s(:long) %></td>
          <td class="table-body" col align="center"><%= event.time.strftime("%-I:%M %p") %></td>
          <td class="table-body" col align="center"><%= event.spots - event.users.size %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= render 'map_script' %>

app/views/events/new.html.erb
<div class="col-md-8 map-container" style="padding-left: 0px;padding-right: 0px; height: 100%">
	<div id="mapnew" style='width: 100%; height: 800px;'></div>
</div>

<div class="col-md-4  whitefullheight">
	
	<br><h1> Create Your New Event</h1>

	<%= render 'form' %>

</div>

<div class="col-md-4" id="directions-panel">
	<h3>Directions and Distance to Selected Park</h3>
</div>
</div>

<%= render 'map_script' %>

app/views/events/show.html.erb
<div class="col-md-8 map-container" style="padding-left: 0px;padding-right: 0px; height: 100%">
	<div id="mapnew" style='width: 100%; height: 800px;'></div>
</div>

<div class="col-md-4 whitefullheight">
</br>
<%= render 'sub_navbar' %>
<div id="wrapper">
	<div class = "event-content">
		<h1><%= @event.title %></h1>
		<h3>at <%= Park.find_by_id(@event.park_id).name %> </h3>			
		<hr>
		<h3>Available spots: <%= @event.spots - @event.users.size %> (of <%= @event.spots %>) </h3>
		<hr>
		<h3>Date: <%= @event.date.to_formatted_s(:long) %></h3>
		<hr>
		<h3>Time: <%= @event.time.strftime("%-I:%M %p") %> </h3>
		<hr>
		<h3>Created by: <%= User.find(@event.creator_id).email %> </h3>
		<hr>
		<h3><%= @event.description %> </h3>

		<% event = current_user.events.find_by_id(params[:id]) %>
		<% creator = @event.creator_id == current_user.id %>
		<% joined = @event.users.exists?(current_user) %>
	</br>
	<%= link_to 'Events', events_path, class: "btn btn-default" %>
	<% if creator %>
	<%= link_to "Edit", edit_event_path(:park_param => @event.park_id), class: "btn btn-warning" %>
	<%= link_to "Delete", event, :method=>:delete , data: { confirm: "Are you sure you want to delete this event?" }, class: "btn btn-danger" %>		
	<% end %>
	<% if joined && !creator %>
	<%= link_to "Unjoin", unjoin_event_path(:id => @event.id), :method=>:patch, class: "btn btn-primary" %>
	<% elsif !creator %>
	<%= link_to "Join", join_event_path(:id => @event.id), :method=>:patch, :disabled => (@event.users.size >= @event.spots), class: "btn btn-primary" %>
	<% end %>
</br>
</br>
<div class="fb-send" data-colorscheme="light"></div>
<div class="fb-share-button" data-layout="button"></div>
</div>
</div>
</div>

<%= render 'map_script' %>