config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'site#homepage'
  resources :events do
    get 'reparse_park_data', on: :collection
    post 'search_events'
  end
  patch 'join' => 'events#join', as: 'join_event'
  patch 'unjoin' => 'events#unjoin', as: 'unjoin_event'
  get 'my_joined_events' => 'events#my_joined_events', as: 'my_joined_events'
  get 'my_created_events' => 'events#my_created_events', as: 'my_created_events'
  get 'this_park_events' => 'events#this_park_events', as: 'this_park_events'
  post '/events/search' => 'events#search', :as => 'search'

  resources :parks do
    get 'reparse_park_data', on: :collection
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  # If you want to authenticate the user first
  protect_from_forgery with: :exception
  # before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || events_path
  end

  private 

  def build_park_array
   @parks = Park.all
   @parksmap = @parks.map{|x| [x.googleMapDest.split(',').first.to_f, x.googleMapDest.split(',').second.to_f, x.name, x.streetNumber, x.streetName, ["Playgrounds"], x.id]}
   @parksmap2 = @parks.map{|x| [x.googleMapDest.split(',').first.to_f, x.googleMapDest.split(',').second.to_f, x.id]}
 end
end

	

app/helpers/application_helper.rb
module ApplicationHelper



end

app/views/application/_map_script.html.erb
 <script>
  $(function(){
    var parks = <%= raw @parksmap %>;
    var title = "<%= raw @title %>"
    var arrayparks = <%= raw @parksmap2 %>
    var typestring = "<%= raw @type %>"
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {styles: mapStyle}, internal: {id: 'mapnew'}}, function(){
      var directionsDisplay = new google.maps.DirectionsRenderer();
      var directionsService = new google.maps.DirectionsService();
      if(navigator.geolocation)
        navigator.geolocation.getCurrentPosition(displayOnMap);
      var arrayhash = initializemap(parks, handler);
      if ( typestring == "index"){
        markers = handler.addMarkers(arrayhash);
        handler.bounds.extendWith(markers);
        markerhandlerparks(markers, arrayparks, directionsService, directionsDisplay);
      } else {
        markers = arrayhash;
        handler.markers = arrayhash.map(function(m) {
          marker = handler.addMarker(m);
          marker.serviceObject.set('id', m["id"]);
          return marker;
        });
        markerhandler(handler.markers, arrayparks, directionsService, directionsDisplay);
        handler.bounds.extendWith(handler.markers);
      }
      handler.fitMapToBounds();
    });
  })
</script>

app/views/application/_sub_navbar.html.erb
<div class="container-fluid nopad">
 <%= link_to events_path, class:"btn btn-primary" do %>
 All Events
 <i class="fa fa-leaf"></i>
 <% end %>
</div>
<div class="container-fluid nopad">
  <%= link_to my_joined_events_path, class:"btn btn-primary" do%>
  Joined Events
  <i class="fa fa-users"></i>
  <% end %>
  <%= link_to my_created_events_path, class:"btn btn-primary" do %>
  My Events
  <i class="fa fa-user"></i>
  <% end %>
  <%= link_to new_event_path, class:"btn btn-primary" do %>
  New Event
  <i class="fa fa-futbol-o"></i>
  <% end %>
</div>
<div class="container-fluid nopad">
  <%= link_to parks_path, class:"btn btn-primary"  do %>
  List All Parks
  <i class="fa fa-tree"></i>
  <% end %>
  <%= link_to reparse_park_data_events_path, class:"btn btn-primary" do%>
  Update Parks
  <i class="fa fa-refresh"></i>
  <% end %>
</div>