config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'site#homepage'
  resources :events do
    get 'reparse_park_data', on: :collection
    post 'search_events'
  end
  patch 'join' => 'events#join', as: 'join_event'
  patch 'unjoin' => 'events#unjoin', as: 'unjoin_event'
  get 'my_joined_events' => 'events#my_joined_events', as: 'my_joined_events'
  get 'my_created_events' => 'events#my_created_events', as: 'my_created_events'
  get 'this_park_events' => 'events#this_park_events', as: 'this_park_events'
  post '/events/search' => 'events#search', :as => 'search'

  resources :parks do
    get 'reparse_park_data', on: :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rack City!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="http://alfredsin.com/images/tree-favicon.png">  
  
</head>
<body>

  <nav class="navbar navbar-fixed-top navbar-intro" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= image_tag("logo.png",class: "navbar-brand") %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <div class="nav navbar-nav navbar-left">

            <li class="navbar-text-custom"> 
              <%= link_to root_url do %>
              <h3 style="margin-top: 0px; margin-bottom: 0px;">
                Rack City
              </h3> 
              <% end %>
            </li>

            <li class="navbar-text-custom"> 
              <%= link_to events_path do %>
              <h3 style="margin-top: 0px; margin-bottom: 0px;">
                Events
              </h3>
              <% end %>  
            </li>
          </div>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li> <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>  </li>  
            <% else %>
            <li> <%= link_to('Sign Up', new_user_registration_path)  %>  </li>
            <li> <%= link_to('Login', new_user_session_path)  %>  </li>
            <% end %>
            <li>  </li>

          </div>
        </ul>
      </div>
    </div>
  </nav>

  <% if notice %>
  <p class="alert alert-success"  id="noticer" style="margin-bottom: 0px;"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"  id="noticer" style="margin-bottom: 0px;"><%= alert %></p>
  <% end %>

  <%= yield %>

</body>

</html>

app/views/layouts/event_park_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rack City!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link rel="icon" href="https://alfredsin.com/images/tree-favicon.png">
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script> 
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-main navbarclassic" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= image_tag("logo.png",class: "navbar-brand") %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-left">
          <div class="nav navbar-nav navbar-left">
           <li class="navbar-text-custom"> 
            <%= link_to root_url do %>
            <h3 style="margin-top: 0px; margin-bottom: 0px;">
              Rack City
            </h3> 
            <% end %>
          </li>

          <form class="navbar-form navbar-left" method="post" accept-charset="UTF-8" action="/events/search" role="search">
            <div class="form-group">
              <input id="query" type="text" class="form-control" name="query" placeholder="Search Events">
            </div>
            <button type="submit" class="btn btn-primary" style="margin-top: 0px;">Submit</button>
          </form>
        </div>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li> <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>  </li>  
          <% else %> 
          <li> <%= link_to('Sign Up', new_user_registration_path)  %>  </li>
          <li> <%= link_to('Login', new_user_session_path)  %>  </li>

          <% end %>
          <li>  </li>
        </div>
      </ul>
    </div>
  </div>
</nav>
<div class='container-fluid' style="padding-top:67px;padding-left:0px;padding-right:0px;">
  <% if notice %>
  <p class="alert alert-success" id="noticer"  style="margin-bottom: 0px;"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"  id="noticer" style="margin-bottom: 0px;"><%= alert %></p>
  <% end %>
</div>
<div>

  <%= yield %>
</div>

</body>
</html>